sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

mysql: &mysql
  adapter: mysql2
  encoding: utf8mb4
  username: root
  password: <%= ENV['MYSQL_PASSWORD'] %>
  database: alchemy_cms_dummy_<%= Rails.env %>

postgresql: &postgresql
  adapter: postgresql
  <% if ENV['POSTGRES_USER'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  <% end %>
  database: alchemy_cms_dummy_<%= Rails.env %>
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "sqlite" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
