- name: header
  unique: true
  contents:
  - name: image
    type: EssencePicture

- name: headline
  contents:
  - name: headline
    type: EssenceText

- name: article
  taggable: true
  contents:
  - name: intro
    type: EssenceText
  - name: headline
    type: EssenceText
    settings:
      linkable: true
  - name: image
    type: EssencePicture
    settings:
      size: 450x300
      crop: true
      fixed_ratio: false
  - name: text
    type: EssenceRichtext

- name: text
  contents:
  - name: text
    type: EssenceRichtext

- name: search
  contents: []

- name: news
  contents:
  - name: date
    type: EssenceDate
  - name: news_headline
    type: EssenceText
    rss_title: true
  - name: body
    type: EssenceRichtext
    rss_description: true

- name: download
  contents:
  - name: file
    type: EssenceFile

- name: bild
  contents:
  - name: image
    type: EssencePicture

- name: contactform
  unique: true
  contents:
  - name: mail_from
    type: EssenceText
    validate:
      - presence
  - name: mail_to
    type: EssenceText
    validate:
      - presence
  - name: subject
    type: EssenceText
    as_element_title: true
    validate:
      - presence
  - name: success_page
    type: EssencePage
    validate:
      - presence

- name: all_you_can_eat
  hint: true
  taggable: true
  contents:
    - name: essence_text
      type: EssenceText
      classes: essence_text_classes
      hint: true
    - name: essence_picture
      type: EssencePicture
      classes: essence_picture_classes
      hint: true
    - name: essence_richtext
      type: EssenceRichtext
      classes: essence_richtext_classes
      hint: true
    - name: essence_select
      type: EssenceSelect
      classes: essence_select_classes
      hint: true
      settings:
        select_values: [A, B, C]
    - name: essence_boolean
      type: EssenceBoolean
      classes: essence_boolean_classes
      hint: true
    - name: essence_date
      type: EssenceDate
      classes: essence_date_classes
      hint: true
    - name: essence_file
      type: EssenceFile
      classes: essence_file_classes
      hint: true
    - name: essence_html
      type: EssenceHtml
      classes: essence_html_classes
      hint: true
    - name: essence_link
      type: EssenceLink
      classes: essence_link_classes
      hint: true

- name: <%= 'erb_' + 'element' %>
  contents:
  - name: text
    type: EssenceRichtext

- name: slide
  compact: true
  contents:
    - name: picture
      type: EssencePicture
    - name: caption
      type: EssenceText
      as_element_title: true

- name: slider
  nestable_elements:
    - slide
  autogenerate:
    - slide

- name: gallery
  nestable_elements:
    - gallery_picture

- name: gallery_picture
  compact: true
  contents:
    - name: picture
      type: EssencePicture
      settings:
        size: 160x120

- name: right_column
  fixed: true
  unique: true
  contents:
    - name: title
      type: EssenceText
  nestable_elements: [search, text]

- name: left_column
  fixed: true
  unique: true
  nestable_elements: [text]

- name: <%= 'erb_' + 'cell' %>
  fixed: true
  unique: true
  nestable_elements: [text]
